mkdir _results
./opencv_perf_bioinspired > resulst/bioinspired.txt
./opencv_perf_calib3d > resulst/calib3d.txt
./opencv_perf_core > resulst/code.txt
./opencv_perf_cudaarithm > resulst/cudaarithm.txt
./opencv_perf_cudabgsegm > resulst/cudabgsegm.txt
./opencv_perf_cudacodec > resulst/cudacodes.txt
./opencv_perf_cudafeatures2d > resulst/cudafeatures2d.txt
./opencv_perf_cudafilters > resulst/cudafilters.txt
./opencv_perf_cudaimgproc > resulst/cudaimgproc.txt
./opencv_perf_cudalegacy > resulst/cudalegasy.txt
./opencv_perf_cudaobjdetect > resulst/cudaobjdetect.txt
./opencv_perf_cudaoptflow > resulst/cudaoptflow.txt
./opencv_perf_cudastereo > resulst/cudastereo.txt
./opencv_perf_cudawarping > resulst/cudawarping.txt
./opencv_perf_dnn > resulst/dnn.txt
./opencv_perf_features2d > resulst/features2d.txt
./opencv_perf_gapi > resulst/gapi.txt
./opencv_perf_imgcodecs > resulst/imgcodecs.txt
./opencv_perf_imgproc > resulst/imgproc.txt
./opencv_perf_line_descriptor > resulst/line_description.txt
./opencv_perf_objdetect > resulst/objdetect.txt
./opencv_perf_optflow > resulst/optflow.txt
./opencv_perf_photo > resulst/photo.txt
./opencv_perf_reg > resulst/reg.txt
./opencv_perf_stereo > resulst/stereo.txt
./opencv_perf_stitching > resulst/stitching.txt
./opencv_perf_superres > resulst/superres.txt
./opencv_perf_tracking > resulst/tracking.txt
./opencv_perf_video > resulst/video.txt
./opencv_perf_videoio > resulst/videoio.txt
./opencv_perf_xfeatures2d > resulst/xfeatures2d.txt
./opencv_perf_ximgproc > resulst/ximgproc.txt
./opencv_perf_xphoto > resulst/xphoto.txt
