#!/bin/sh
mkdir _results
time -p ./opencv_perf_bioinspired > _results/bioinspired.txt
time -p ./opencv_perf_calib3d > _results/calib3d.txt
time -p ./opencv_perf_core > _results/core.txt
time -p ./opencv_perf_cudaarithm > _results/cudaarithm.txt
time -p ./opencv_perf_cudabgsegm > _results/cudabgsegm.txt
time -p ./opencv_perf_cudacodec > _results/cudacodes.txt
time -p ./opencv_perf_cudafeatures2d > _results/cudafeatures2d.txt
time -p ./opencv_perf_cudafilters > _results/cudafilters.txt
time -p ./opencv_perf_cudaimgproc > _results/cudaimgproc.txt
time -p ./opencv_perf_cudalegacy > _results/cudalegasy.txt
time -p ./opencv_perf_cudaobjdetect > _results/cudaobjdetect.txt
time -p ./opencv_perf_cudaoptflow > _results/cudaoptflow.txt
time -p ./opencv_perf_cudastereo > _results/cudastereo.txt
time -p ./opencv_perf_cudawarping > _results/cudawarping.txt
time -p ./opencv_perf_dnn > _results/dnn.txt
time -p ./opencv_perf_features2d > _results/features2d.txt
time -p ./opencv_perf_gapi > _results/gapi.txt
time -p ./opencv_perf_imgcodecs > _results/imgcodecs.txt
time -p ./opencv_perf_imgproc > _results/imgproc.txt
time -p ./opencv_perf_line_descriptor > _results/line_description.txt
time -p ./opencv_perf_objdetect > _results/objdetect.txt
time -p ./opencv_perf_optflow > _results/optflow.txt
time -p ./opencv_perf_photo > _results/photo.txt
time -p ./opencv_perf_reg > _results/reg.txt
time -p ./opencv_perf_stereo > _results/stereo.txt
time -p ./opencv_perf_stitching > _results/stitching.txt
time -p ./opencv_perf_superres > _results/superres.txt
time -p ./opencv_perf_tracking > _results/tracking.txt
time -p ./opencv_perf_video > _results/video.txt
time -p ./opencv_perf_videoio > _results/videoio.txt
time -p ./opencv_perf_xfeatures2d > _results/xfeatures2d.txt
time -p ./opencv_perf_ximgproc > _results/ximgproc.txt
time -p ./opencv_perf_xphoto > _results/xphoto.txt
