#!/bin/sh
mkdir _results
time -p ./opencv_perf_bioinspired > results/bioinspired.txt
time -p ./opencv_perf_calib3d > results/calib3d.txt
time -p ./opencv_perf_core > results/code.txt
time -p ./opencv_perf_cudaarithm > results/cudaarithm.txt
time -p ./opencv_perf_cudabgsegm > results/cudabgsegm.txt
time -p ./opencv_perf_cudacodec > results/cudacodes.txt
time -p ./opencv_perf_cudafeatures2d > results/cudafeatures2d.txt
time -p ./opencv_perf_cudafilters > results/cudafilters.txt
time -p ./opencv_perf_cudaimgproc > results/cudaimgproc.txt
time -p ./opencv_perf_cudalegacy > results/cudalegasy.txt
time -p ./opencv_perf_cudaobjdetect > results/cudaobjdetect.txt
time -p ./opencv_perf_cudaoptflow > results/cudaoptflow.txt
time -p ./opencv_perf_cudastereo > results/cudastereo.txt
time -p ./opencv_perf_cudawarping > results/cudawarping.txt
time -p ./opencv_perf_dnn > results/dnn.txt
time -p ./opencv_perf_features2d > results/features2d.txt
time -p ./opencv_perf_gapi > results/gapi.txt
time -p ./opencv_perf_imgcodecs > results/imgcodecs.txt
time -p ./opencv_perf_imgproc > results/imgproc.txt
time -p ./opencv_perf_line_descriptor > results/line_description.txt
time -p ./opencv_perf_objdetect > results/objdetect.txt
time -p ./opencv_perf_optflow > results/optflow.txt
time -p ./opencv_perf_photo > results/photo.txt
time -p ./opencv_perf_reg > results/reg.txt
time -p ./opencv_perf_stereo > results/stereo.txt
time -p ./opencv_perf_stitching > results/stitching.txt
time -p ./opencv_perf_superres > results/superres.txt
time -p ./opencv_perf_tracking > results/tracking.txt
time -p ./opencv_perf_video > results/video.txt
time -p ./opencv_perf_videoio > results/videoio.txt
time -p ./opencv_perf_xfeatures2d > results/xfeatures2d.txt
time -p ./opencv_perf_ximgproc > results/ximgproc.txt
time -p ./opencv_perf_xphoto > results/xphoto.txt
